# TAO Toolkit API container info
image:
  repository: nvcr.io/nvidia/tao/tao-api
  tag: v5.5.0-nightly-latest

hostBaseUrl: "http://10.123.4.56:32080"
imagePullSecret: imagepullsecret
imagePullPolicy: Always

serviceAdminUUID: 02a55e1e-0091-4711-b29e-12a61c0d29bf # str(uuid.uuid5(uuid.UUID(int=0), str(ngc_user_id)))

# Optional proxy settings
#httpsProxy: http://10.194.54.59:3128
#myCertConfig: my-cert

# Optional JupyterLab service
ngcCollaterals: nvidia/tao/tao-getting-started:5.5.0
notebooksDir: tao-getting-started_v5.5.0/notebooks/tao_api_starter_kit

profiler: "False"


# Optional telemetry gateway
# Uncomment this when telemetry gateway is needed. Podmonitor Crd needs to be present in cluster.
# enableTelemetry: False
# telemetry:
#   image:
#     repository: nvcr.io/nvidia/tao/tao-telemetry-gateway
#     tag: latest
#   pollingIntervalSeconds: 10
#   exporterPort: 9877

# Optional HTTPS settings for ingress controller
#host: mydomain.com
#tlsSecret: tls-secret
#corsOrigin: https://mydomain.com

# Shared storage info
storageClassName: nfs-client
storageAccessMode: ReadWriteMany
storageSize: 900Gi

#authClientId: bnSePYullXlG-504nOZeNAXemGF6DhoCdYR8ysm088w

deploymentMode: "PROD" # STAGING/PROD
backend: local-k8s
maxNumGpuPerNode: 1

imagePyt: nvcr.io/nvidia/tao/tao-toolkit:5.5.0-pyt
imageTf2: nvcr.io/nvidia/tao/tao-toolkit:5.0.0-tf2.11.0
imageTaoDeploy: nvcr.io/nvidia/tao/tao-toolkit:5.5.0-deploy
imageDataservices: nvcr.io/nvidia/tao/tao-toolkit:5.5.0-data-services
imageDefault: nvcr.io/nvidia/tao/tao-toolkit:5.5.0-pyt

# To opt out of providing anonymous telemetry data to NVIDIA
#telemetryOptOut: no
