# TAO Toolkit API container info
image:
  repository: nvcr.io/nvstaging/tao/nvtl-api
  tag: v5.2.0-nightly-latest
imagePullSecret: imagepullsecret
imagePullPolicy: Always

# Optional proxy settings
#httpsProxy: http://10.194.54.59:3128
#myCertConfig: my-cert

# Optional JupyterLab service
ngcCollaterals: nvidia/tao/tao-getting-started:5.0.0
notebooksDir: notebooks
# notebooksDir: tao-getting-started_v5.0.0/notebooks/tao_api_starter_kit

# NGC API BASE URL
#ngcApiBaseUrl: https://api.ngc.nvidia.com/v2

# Optional HTTPS settings for ingress controller
#host: mydomain.com
#tlsSecret: tls-secret
#corsOrigin: https://mydomain.com

# Shared storage info
storageClassName: nfs-client
storageAccessMode: ReadWriteMany
storageSize: 900Gi

# Authentication
#authClientId: bnSePYullXlG-504nOZeNAXemGF6DhoCdYR8ysm088w

adminUUID: "00000000-0000-0000-0000-000000000001"

backend: local-k8s
maxNumGpuPerNode: 1
imageTf1: nvcr.io/nvidia/tao/tao-toolkit:5.0.0-tf1.15.5
imagePyt: nvcr.io/nvstaging/tao/tao-toolkit-pyt_v5.2.0-nightly-latest
imageTf2: nvcr.io/nvidia/tao/tao-toolkit:5.0.0-tf2.11.0
imageTaoDeploy: nvcr.io/nvstaging/tao/tao-toolkit-deploy_v5.2.0-nightly-latest
imageDataservices: nvcr.io/nvstaging/tao/tao-toolkit-ds_v5.0.0-nightly-latest
imageDefault: nvcr.io/nvidia/tao/tao-toolkit:5.0.0-tf1.15.5
