# TAO Toolkit API container info
image:
  repository: nvcr.io/nvidia/tao/tao-toolkit
  tag: 5.2.0-api
imagePullSecret: imagepullsecret
imagePullPolicy: Always

# Optional proxy settings
#httpsProxy: http://10.194.54.59:3128
#myCertConfig: my-cert

# Optional JupyterLab service
ngcCollaterals: nvidia/tao/tao-getting-started:5.2.0
notebooksDir: tao-getting-started_v5.2.0/notebooks/tao_api_starter_kit

# Optional HTTPS settings for ingress controller
#host: mydomain.com
#tlsSecret: tls-secret
#corsOrigin: https://mydomain.com

# Shared storage info
storageClassName: nfs-client
storageAccessMode: ReadWriteMany
storageSize: 900Gi

# Optional NVIDIA Starfleet authentication
#authClientId: bnSePYullXlG-504nOZeNAXemGF6DhoCdYR8ysm088w

# Starting TAO Toolkit jobs info
backend: local-k8s
maxNumGpuPerNode: 1
imageTf1: nvcr.io/nvidia/tao/tao-toolkit:5.0.0-tf1.15.5
imagePyt: nvcr.io/nvidia/tao/tao-toolkit:5.2.0-pyt2.1.0
imagePyt_114: nvcr.io/nvidia/tao/tao-toolkit:5.2.0-pyt1.14.0
imageTf2: nvcr.io/nvidia/tao/tao-toolkit:5.0.0-tf2.11.0
imageTaoDeploy: nvcr.io/nvidia/tao/tao-toolkit:5.2.0-deploy
imageDataservices: nvcr.io/nvidia/tao/tao-toolkit:5.2.0-data-services
imageDefault: nvcr.io/nvidia/tao/tao-toolkit:5.0.0-tf1.15.5

# To opt out of providing anonymous telemetry data to NVIDIA
#telemetryOptOut: no