# Copyright (c) 2024, NVIDIA CORPORATION.  All rights reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-app-pod
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Release.Name }}-app-pod
spec:
  replicas: 1
  selector:
    matchLabels:
      name: {{ .Release.Name }}-app-pod
  template:
    metadata:
{{- if .Values.enableVault }}
      {{- with.Values.vault.pod.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
      name: {{ .Release.Name }}-app-pod
      namespace: {{ .Release.Namespace }}
      labels:
        name: {{ .Release.Name }}-app-pod
    spec:
      containers:
      - name: {{ .Release.Name }}-app
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        securityContext:
          privileged: true
        imagePullPolicy: {{ .Values.imagePullPolicy | default "Always" }}
        env:
        - name: NAMESPACE
          value: {{ .Release.Namespace | quote }}
        - name: CLAIMNAME
          value: "{{ .Release.Name }}-pvc"
        - name: IMAGEPULLSECRET
          value: {{ .Values.imagePullSecret | default "imagepullsecret" | quote }}
        - name: AUTH_CLIENT_ID
          value: {{ .Values.authClientId | default "bnSePYullXlG-504nOZeNAXemGF6DhoCdYR8ysm088w" | quote }}
        - name: NUM_GPU_PER_NODE
          value: {{ .Values.maxNumGpuPerNode | default "1" | quote }}
        - name: BACKEND
          value: {{ .Values.backend | default "local-k8s" | quote }}
        - name: IMAGE_TF1
          value: {{ .Values.imageTf1 | default "nvcr.io/nvidia/tao/tao-toolkit:5.0.0-tf1.15.5" | quote }}
        - name: IMAGE_PYT
          value: {{ .Values.imagePyt | default "nvcr.io/nvidia/tao/tao-toolkit:5.2.0-pyt2.1.0" | quote }}
        - name: IMAGE_TF2
          value: {{ .Values.imageTf2 | default "nvcr.io/nvidia/tao/tao-toolkit:5.0.0-tf2.11.0" | quote }}
        - name: IMAGE_TAO_DEPLOY
          value: {{ .Values.imageTaoDeploy | default "nvcr.io/nvidia/tao/tao-toolkit:5.2.0-deploy" | quote }}
        - name: IMAGE_DEFAULT
          value: {{ .Values.imageDefault | default "nvcr.io/nvidia/tao/tao-toolkit:5.0.0-tf1.15.5" | quote }}
        - name: IMAGE_API
          value: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        - name: IMAGE_DATA_SERVICES
          value: {{ .Values.imageDataservices | default "nvcr.io/nvidia/tao/tao-toolkit:5.2.0-data-services" | quote }}
        - name: ADMIN_UUID
          value: {{ .Values.adminUUID | default "00000000-0000-0000-0000-000000000001" | quote }}
        - name: MAX_GPU_PER_USER_REALTIME_INFER
          value: {{ .Values.maxGpuPerUserRealtimeInfer | default "2" | quote }}
        - name: PYTHONIOENCODING 
          value: utf-8
        - name: LC_ALL 
          value: C.UTF-8 
{{- if .Values.httpsProxy }}
        - name: HTTPS_PROXY
          value: {{ .Values.httpsProxy | default "" | quote }}
        - name: https_proxy
          value: {{ .Values.httpsProxy | default "" | quote }}
{{- end }}
{{- if .Values.myCertConfig }}
        - name: CURL_CA_BUNDLE
          value: "/etc/ssl/certs/ca-certificates.crt"
        - name: REQUESTS_CA_BUNDLE
          value: "/etc/ssl/certs/ca-certificates.crt"
        - name: SSL_CERT_FILE
          value: "/etc/ssl/certs/ca-certificates.crt"
{{- end }}
{{- if .Values.enableVault }}
        - name: VAULT_SECRET_PATH
          value: "{{ .Values.vault.secretMountPath }}"
{{- end }}
        - name: NGC_API_BASE_URL
          value: {{ .Values.ngcApiBaseUrl | default "https://api.ngc.nvidia.com/v2" | quote }}
        ports:
        - containerPort: 8000
        volumeMounts:
        - name: shared-data
          mountPath: /shared
{{- if .Values.myCertConfig }}
        - name: my-cert
          mountPath: /usr/local/share/ca-certificates/
{{- end }}
{{- if .Values.enableVault }}
        - name: token
          mountPath: {{ .Values.vault.volumeMounts.tokenPath }}
{{- end }}
        livenessProbe:
          httpGet:
           path: /api/v1/health/liveness
           port: 8000
          initialDelaySeconds: 3
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
           path: /api/v1/health/readiness
           port: 8000
          initialDelaySeconds: 3
          timeoutSeconds: 3
          periodSeconds: 10
          failureThreshold: 3
      terminationGracePeriodSeconds: 3
{{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
{{- end }}
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc
{{- if .Values.myCertConfig }}
      - name: my-cert
        configMap:
          name: {{ .Values.myCertConfig }}
          items:
          - key: my-cert.crt
            path: my-cert.crt
{{- end }}
{{- if .Values.enableVault }}
      - name: token
        projected:
          sources:
            - serviceAccountToken:
                audience: {{ .Values.vault.volumes.projected.serviceAccountToken.audience }}:443
                expirationSeconds: 3600
                path: token
{{- end }}
