apiVersion: apps/v1
kind: Deployment
metadata:
  name: dgx-job-controller
spec:
  selector:
    matchLabels:
      app: dgx-job-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: dgx-job-controller
    spec:
      containers:
      - name: dgx-job-controller
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: ["python3", "dgx_controller.py"]
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        imagePullPolicy: {{ .Values.imagePullPolicy | default "Always" }}
        env:
        - name: NAMESPACE
          value: {{ .Release.Namespace | quote }}
        - name: CLAIMNAME
          value: "{{ .Release.Name }}-pvc"
        - name: IMAGEPULLSECRET
          value: {{ .Values.imagePullSecret | default "imagepullsecret" | quote }}
        - name: BACKEND
          value: {{ .Values.backend | default "local-k8s" | quote }}
        - name: IMAGE_API
          value: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        - name: CALLBACK_UUID
          value: {{ .Values.serviceAdminUUID | default "02a55e1e-0091-4711-b29e-12a61c0d29bf" | quote }}
        - name: MONGOSECRET
          valueFrom:
            secretKeyRef:
              name: {{ .Values.imagePullSecret | default "imagepullsecret" | quote }}
              key: .dockerconfigjson
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc
{{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
{{- end }}