apiVersion: apps/v1
kind: Deployment
metadata:
  name: dgx-job-controller
spec:
  selector:
    matchLabels:
      app: dgx-job-controller
  replicas: 1
  template:
    metadata:
      labels:
        app: dgx-job-controller
    spec:
      containers:
      - name: dgx-job-controller
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: ["python3", "dgx_controller.py"]
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        imagePullPolicy: {{ .Values.imagePullPolicy | default "Always" }}
        env:
        - name: NAMESPACE
          value: {{ .Release.Namespace | quote }}
        - name: CLAIMNAME
          value: "{{ .Release.Name }}-pvc"
        - name: IMAGEPULLSECRET
          value: {{ .Values.imagePullSecret | default "imagepullsecret" | quote }}
        - name: NGC_RUNNER
          value: {{ .Values.ngcRunner | default "False" | quote }}
        - name: IMAGE_API
          value: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc
{{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
{{- end }}