apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: dgxjobs.dgx-job-manager.nvidia.io
spec:
  group: dgx-job-manager.nvidia.io
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                user_id:
                  type: string
                job_id:
                  type: string
                name:
                  type: string
                dockerImageName:
                  type: string
                command:
                  type: string
                runPolicy:
                  type: object
                  properties:
                    preemptClass:
                      type: string
                envs:
                  type: array
                  items:
                    type: object
                    properties:
                      name:
                        type: string
                      value:
                        type: string
                workspaceMounts:
                  type: array
                  items:
                    type: object
                    properties:
                      containerMountPoint:
                        type: string
                      id:
                        type: string
                      mountMode:
                        type: string
                namespace:
                  type: string
                orgName:
                  type: string
                teamName:
                  type: string
                aceName:
                  type: string
                aceInstance:
                  type: string
                resultContainerMountPoint:
                  type: string
            status:
              type: object
              properties:
                phase:
                  type: string
  names:
    plural: dgxjobs
    singular: dgxjob
    listKind: DgxJobList
    kind: DgxJob
    shortNames:
    - dj
