apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvcf-job-controller
spec:
  selector:
    matchLabels:
      app: nvcf-job-controller
  replicas: 1
  template:
    metadata:
{{- if .Values.enableVault }}
      {{- with.Values.vault.pod.annotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
        {{- end }}
{{- end }}
      labels:
        app: nvcf-job-controller
    spec:
      containers:
      - name: nvcf-job-controller
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        command: ["python3", "nvcf_controller.py"]
        volumeMounts:
        - name: shared-data
          mountPath: /shared
{{- if .Values.enableVault }}
        - name: token
          mountPath: {{ .Values.vault.volumeMounts.tokenPath }}
{{- end }}
        imagePullPolicy: {{ .Values.imagePullPolicy | default "Always" }}
        env:
        - name: NAMESPACE
          value: {{ .Release.Namespace | quote }}
        - name: CLAIMNAME
          value: "{{ .Release.Name }}-pvc"
        - name: IMAGEPULLSECRET
          value: {{ .Values.imagePullSecret | default "imagepullsecret" | quote }}
        - name: BACKEND
          value: {{ .Values.backend | default "local-k8s" | quote }}
        - name: IMAGE_API
          value: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        - name: CALLBACK_UUID
          value: {{ .Values.serviceAdminUUID | default "02a55e1e-0091-4711-b29e-12a61c0d29bf" | quote }}
{{- if .Values.enableVault }}
        - name: VAULT_SECRET_PATH
          value: "{{ .Values.vault.secretMountPath }}"
{{- end }}
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc
{{- if .Values.enableVault }}
      - name: token
        projected:
          sources:
            - serviceAccountToken:
                audience: {{ .Values.vault.volumes.projected.serviceAccountToken.audience }}:443
                expirationSeconds: 3600
                path: token
{{- end }}
{{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret }}
{{- end }}