apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: nvcfjobs.nvcf-job-manager.nvidia.io
spec:
  group: nvcf-job-manager.nvidia.io
  scope: Namespaced
  versions:
    - name: v1alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                org_name:
                  type: string
                action:
                  type: string
                workspace_ids:
                  type: array
                  items:
                    type: string
                deployment_string:
                  type: string
                container:
                  type: string
                job_id:
                  type: string
                network:
                  type: string
                ngc_api_key:
                  type: string
                spec_file_path:
                  type: string
                tao_api_admin_key:
                  type: string
                tao_api_base_url:
                  type: string
                tao_api_status_callback_url:
                  type: string
                tao_api_ui_cookie:
                  type: string
                use_ngc_staging:
                  type: string
                automl_experiment_number:
                  type: string
            status:
              type: object
              properties:
                phase:
                  type: string
  names:
    plural: nvcfjobs
    singular: nvcfjob
    listKind: NvcfJobList
    kind: NvcfJob
    shortNames:
    - dj
