{{- if .Values.enableTelemetry -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-telemetry-pod
  namespace: {{ .Release.Namespace }}
  labels:
    name: {{ .Release.Name }}-telemetry-pod
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-telemetry-pod
  template:
    metadata:
      labels:
        name: {{ .Release.Name }}-telemetry-pod
    spec:
      containers:
      - name: {{ .Release.Name }}-telemetry
        image: {{ .Values.telemetry.image.repository }}:{{ .Values.telemetry.image.tag }}
        ports:
        - name: exporter
          containerPort: {{ .Values.telemetry.exporterPort | default 9877 }}
          protocol: TCP
        volumeMounts:
        - name: shared-data
          mountPath: /shared
        imagePullPolicy: {{ .Values.imagePullPolicy | default "Always" }}
        env:
        - name: NAMESPACE
          value: {{ .Release.Namespace | quote }}
        - name: POLLING_INTERVAL_SECONDS
          value: {{ .Values.telemetry.pollingIntervalSeconds | default "10" | quote }}
        - name: EXPORTER_PORT
          value: {{ .Values.telemetry.exporterPort | default "9877" | quote }}
{{- if .Values.imagePullSecret }}
      imagePullSecrets:
      - name: {{ .Values.imagePullSecret | default "imagepullsecret" | quote }}
{{- end }}
      volumes:
      - name: shared-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-pvc
---
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ .Release.Name }}-telemetry-pod-monitor
  labels:
    platform.nvidia.com/monitoring: enabled
spec:
  selector:
    matchLabels:
      name: {{ .Release.Name }}-telemetry-pod
  podMetricsEndpoints:
  - port: exporter
    interval: 10s

{{- end }}
